### ISSUE TITLE
Container Support

### ISSUE THREAD

**Issue by ymd-h** [keiohta/tf2rl#110]
I will send PR to support docker container.

**Comment by ymd-h** [comment]
@keiohta 

I think you forget to make containers public.

Even though Actions succeeded in pushing to the registry, no containers are shown.
(https://github.com/keiohta/tf2rl/runs/1289373145?check_suite_focus=true)


Please access following two links and press "Make public" in danger zone. (Only @keiohta can see.)
https://github.com/users/keiohta/packages/container/tf2rl%2Fcpu/settings
https://github.com/users/keiohta/packages/container/tf2rl%2Fnvidia/settings

**Comment by keiohta** [comment]
Hi @ymd-h , thanks for pointing out the problem.
I've made them public, so could you check if I successfully solved the problem? Or, do I need to push something to pull the trigger?

**Comment by ymd-h** [comment]
@keiohta  Thanks for replying!

Yes, you are right. I found them at your profile. (Maybe you've made them public 4 days ago? sorry.)
https://github.com/keiohta?tab=packages

Probably, I misunderstand that they should be shown at tf2rl repository like old packages, but that is not the case.
