### ISSUE TITLE
Add recent version of TensorFlow

### ISSUE THREAD

**Issue by sff1019** [keiohta/tf2rl#135]
Thank you for this amazing library!

Currently, tf2rl supports only tf_version <= 2.3.0, according to the setup file. Would it be possible to add newer versions of Tensorflow (e.g. 2.4.0)?

**Comment by sff1019** [comment]
Ran `bash ./test_run_examples.sh` without any errors.

**Comment by keiohta** [comment]
Thanks for creating this issue and checked tf2.4 works!
I just verified it works too. I'll update master branch soon.

**Comment by sff1019** [comment]
Just in case, to reduce workload on your side I've just created a new [PR#136](https://github.com/keiohta/tf2rl/pull/136).

**Comment by keiohta** [comment]
I merged your PR, and closing this issue. Thanks for your help !
