### ISSUE TITLE
Implement VAIL

### ISSUE THREAD

**Issue by keiohta** [keiohta/tf2rl#14]
[Variational Discriminator Bottleneck: Improving Imitation Learning, Inverse RL, and GANs by Constraining Information Flow](https://arxiv.org/abs/1810.00821)

**Comment by keiohta** [comment]
### Experiment on Pendulum-v0

```bash
# Generate expert trajectories
$ python examples/run_sac.py --env-name=Pendulum-v0 --save-test-path --test-interval=100000 --max-steps 100000 --test-episodes=20 --gpu -1

# VAIL
$ python examples/run_vail_ddpg.py --env-name=Pendulum-v0 --test-interval=5000 --expert-path-dir results/20190706T231341.308287_SAC_ --gpu -1
# VAIL with Spectral Normalization
$ python examples/run_vail_ddpg.py --env-name=Pendulum-v0 --test-interval=5000 --expert-path-dir results/20190706T231341.308287_SAC_ --gpu -1 --enable-sn --dir-suffix SN
```

#### Results
- Score
    - The maximum score is 0.
    - VAIL is unstable. Adding Spectral Normalization stabilizes learning and improves score.
<img width="230" alt="190707_VAIL_Pendulum_score" src="https://user-images.githubusercontent.com/7234712/60762518-49348880-a09d-11e9-9796-6d35288f035e.png">

- DDPG loss
<img width="454" alt="190707_VAIL_Pendulum_DDPG_loss" src="https://user-images.githubusercontent.com/7234712/60762519-52255a00-a09d-11e9-9e05-da0f10a9ed68.png">
 
- VAIL
<img width="1126" alt="190707_VAIL_Pendulum_info" src="https://user-images.githubusercontent.com/7234712/60762533-8b5dca00-a09d-11e9-9267-52550f874601.png">

**Comment by keiohta** [comment]
### Experiment on HalfCheetah-v2
```bash
# Generate expert trajectories
$ python examples/run_sac.py --env-name=HalfCheetah-v2 --save-test-path --test-interval=500000 --max-steps 500000 --test-episodes=20 --gpu -1

# VAIL
$ python examples/run_vail_ddpg.py --env-name=HalfCheetah-v2 --test-interval=5000 --expert-path-dir results/20190707T094429.686303_SAC_ --gpu -1
# VAIL_SN
$ python examples/run_vail_ddpg.py --env-name=HalfCheetah-v2 --test-interval=5000 --expert-path-dir results/20190707T094429.686303_SAC_ --gpu -1 --enable-sn --dir-suffix _SN

# GAIL
$ python examples/run_gail_ddpg.py --env-name=HalfCheetah-v2 --test-interval=5000 --expert-path-dir results/20190707T094429.686303_SAC_ --gpu -1
# GAIL_SN
$ python examples/run_gail_ddpg.py --env-name=HalfCheetah-v2 --test-interval=5000 --expert-path-dir results/20190707T094429.686303_SAC_ --gpu -1 --enable-sn --dir-suffix _SN
```

#### Results
- All algorithm reproduced the expert score (~9000)
- No big difference between GAIL, VAIL even utilizing Spectral Normalization
    - Gray: VAIL, Orange: VAIL + SN, Red: GAIL, Blue: GAIL + SN

#### TensorBoard output
- Score
<img width="457" alt="190707_VAIL_GAIL_HalfCheetah_score" src="https://user-images.githubusercontent.com/7234712/60774485-62960d00-a14f-11e9-8495-c0f70c521432.png">
- VAIL
<img width="460" alt="190707_VAIL_HalfCheetah" src="https://user-images.githubusercontent.com/7234712/60774486-62960d00-a14f-11e9-8b87-372d4785d422.png">
- GAIL
<img width="455" alt="190707_GAIL_HalfCheetah" src="https://user-images.githubusercontent.com/7234712/60774482-61fd7680-a14f-11e9-9f79-07f6efd356df.png">
- DDPG loss
<img width="453" alt="190707_VAIL_GAIL_HalfCheetah_DDPG_loss" src="https://user-images.githubusercontent.com/7234712/60774483-61fd7680-a14f-11e9-9fb3-d9b7dc28ad04.png">

**Comment by keiohta** [comment]
https://github.com/keiohta/tf2rl/commit/4535cfb33eb0ee11ead9df052f7f13a0309baa26

**Comment by sasayesh** [comment]
Hi @keiohta 
I couldn't reproduce the same results, I got this error for HalfCheetah:
Traceback (most recent call last):
  File "examples/run_vail_ddpg.py", line 44, in <module>
    trainer()
  File "/home/ss/.local/lib/python3.8/site-packages/tf2rl/experiments/irl_trainer.py", line 51, in __call__
    next_obs, reward, done, _ = self._env.step(action) ##
  File "/home/ss/.local/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 16, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/ss/.local/lib/python3.8/site-packages/gym/envs/mujoco/half_cheetah.py", line 12, in step
    self.do_simulation(action, self.frame_skip)
  File "/home/ss/.local/lib/python3.8/site-packages/gym/envs/mujoco/mujoco_env.py", line 125, in do_simulation
    self.sim.step()
  File "mujoco_py/mjsim.pyx", line 126, in mujoco_py.cymj.MjSim.step
  File "mujoco_py/cymj.pyx", line 156, in mujoco_py.cymj.wrap_mujoco_warning.__exit__
  File "mujoco_py/cymj.pyx", line 77, in mujoco_py.cymj.c_warning_callback
  File "/home/ss/projects/mujoco-py/mujoco_py/builder.py", line 363, in user_warning_raise_exception
    raise MujocoException(warn + 'Check for NaN in simulation.')
mujoco_py.builder.MujocoException: Unknown warning type Time = 24.7000.Check for NaN in simulation.
**OS: Ubuntu 20**
**TF version: tested on 2.3 and 2.4**
**tf2rl: Master**
Your input would be appreciated.

**Comment by keiohta** [comment]
Hi @sasayesh , thanks for reporting the error. I'll try to reproduce the bug on Wednesday.
