### ISSUE TITLE
Setting step size in trainer.py for evaluate policy

### ISSUE THREAD

**Issue by naji-s** [keiohta/tf2rl#142]
From what I can read in the code here: https://github.com/keiohta/tf2rl/blob/82d9eecda78e22021efa0821bf02429ac7827f4d/tf2rl/experiments/trainer.py#L180

the total_steps is only set in the summary of tf, and I believe one needs to replace self._episode_max_steps in 
https://github.com/keiohta/tf2rl/blob/82d9eecda78e22021efa0821bf02429ac7827f4d/tf2rl/experiments/trainer.py#L195

with total_steps

**Comment by ymd-h** [comment]
@naji-s 

The argument `total_steps` at `evaluate_policy` function is a **current** total steps, is not the maximum episode horizon.
It is used for x-axis of evaluation graph, so that we can see the evolution of policy performance during training.

**Comment by naji-s** [comment]
I see. Thanks for the explanation.
