### ISSUE TITLE
Fix coverage badge is not shown

### ISSUE THREAD

**Issue by keiohta** [keiohta/tf2rl#24]
[Coverage badge](https://coveralls.io/github/keiohta/tf2rl) is unknown for some reasons. Fix this.

**Comment by yamada-github-account** [comment]
The following warning can be a (one of the) reason.
https://travis-ci.org/keiohta/tf2rl/jobs/537501109#L442

There is a possibly related issue.
https://bitbucket.org/ned/coveragepy/issues/567/source-coveragepy-warning-module-xxxpy-was

Do you have (or install) `cookiecutter` and `import` it?

---

Additionally I put a StackOverflow [link](https://stackoverflow.com/questions/47287721/coverage-py-warning-no-data-was-collected-no-data-collected) which mentions "no-data-collected"

**Comment by keiohta** [comment]
Thank you for the information! I fixed.
