### ISSUE TITLE
Which branch is stable?

### ISSUE THREAD

**Issue by XiuYuanInTheQuest** [keiohta/tf2rl#48]

**Comment by keiohta** [comment]
[master branch](https://github.com/keiohta/tf2rl/tree/master) should be stable. If you find a bug, I would like you to report as an issue.
Thanks.

**Comment by XiuYuanInTheQuest** [comment]
ok

**Comment by XiuYuanInTheQuest** [comment]
Which version of tensorflow do you use? Alpha or beta?

**Comment by keiohta** [comment]
Currently use `tensorflow==2.0.0b0` or `tensorflow-gpu==2.0.0b0`.

**Comment by XiuYuanInTheQuest** [comment]
thanks

**Comment by XiuYuanInTheQuest** [comment]
I installed cpprb error, saying that Microsoft Visual C++ Build Tools is missing, but I still get an error after I install Microsoft Visual C++ Build Tools 2015. What solutions do you have?

**Comment by keiohta** [comment]
I actually haven't tried installing tf2rl on Windows for a long time, but I remember using `gcc>=7.2.0` to install [cpprb](https://gitlab.com/ymd_h/cpprb) solved the problem, not msvc.
Can you try using gcc? If not, I will try with msvc but need time.

**Comment by XiuYuanInTheQuest** [comment]
Thank you, let me try gcc.

**Comment by XiuYuanInTheQuest** [comment]
![image](https://user-images.githubusercontent.com/44158381/64523512-05752e00-d32f-11e9-91a5-be3d97956124.png)

**Comment by XiuYuanInTheQuest** [comment]
![image](https://user-images.githubusercontent.com/44158381/64523558-25a4ed00-d32f-11e9-961f-756da418a092.png)
I installed gcc14 with cygwin64, but still failed to install cpprb.

**Comment by XiuYuanInTheQuest** [comment]
![image](https://user-images.githubusercontent.com/44158381/64523734-93511900-d32f-11e9-9c7c-66ee26dd513a.png)
I installed gcc14 with cygwin64, but still failed to install cpprb.

**Comment by XiuYuanInTheQuest** [comment]
![image](https://user-images.githubusercontent.com/44158381/64523817-b976b900-d32f-11e9-82ce-a52e88520ffd.png)
I installed gcc7.4.0 with cygwin64, but still failed to install cpprb.

**Comment by keiohta** [comment]
@yamada-github-account Do you have any idea to solve this?

**Comment by XiuYuanInTheQuest** [comment]
I successfully installed all the packages on ubuntu, but this place was wrong

**Comment by XiuYuanInTheQuest** [comment]
Traceback (most recent call last):
  File "/home/wk/PycharmProjects/tf2rl/examples/run_ddpg.py", line 5, in <module>
    from tf2rl.experiments.trainer import Trainer
  File "/home/wk/PycharmProjects/tf2rl/tf2rl/experiments/trainer.py", line 13, in <module>
    logging.root.handlers[0].setFormatter(logging.Formatter(
IndexError: list index out of range

**Comment by keiohta** [comment]
Oh, thank you for letting me know that. It's a trick to change logging setting that is changed by TensorFlow.
Now I know better way to handle this logging setting, so I'll fix this bug tomorrow.

**Comment by XiuYuanInTheQuest** [comment]
This bug was created by running tf2rl/examples/run ddpg.py

**Comment by keiohta** [comment]
Thank you. I know the reason why, just need couple of hours :)

**Comment by XiuYuanInTheQuest** [comment]
Have you fixed the bug yet?

**Comment by XiuYuanInTheQuest** [comment]
![image](https://user-images.githubusercontent.com/44158381/65386186-ac63bc00-dd6a-11e9-9671-c4574bd41739.png)

**Comment by keiohta** [comment]
Hi, I'm sorry for replying late. I've been super busy these days for writing paper...
I fixed the bug, so can you try following:
```bash
$ git checkout -b fix_logger_setting origin/fix_logger_setting
# If you do not have GPU, add `--gpu -1` option
$ python examples/run_ddpg.py
```
, and if you might have problem, please let me know.

**Comment by XiuYuanInTheQuest** [comment]
Thank you very much. Is your research direction deep reinforcement learning?

**Comment by keiohta** [comment]
You're very welcome!

Yes, my research direction is deep reinforcement learning (both model-free and model-based) especially for robotic problems.

**Comment by XiuYuanInTheQuest** [comment]
That's great. I've also been studying reinforcement recently and want to send out papers in this direction, so I'm learning your code.

**Comment by XiuYuanInTheQuest** [comment]
Now I have another problem. It seems that tf. function does not work.

**Comment by XiuYuanInTheQuest** [comment]
WARNING:tensorflow:Entity <bound method DQN._train_body of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f9b06b425f8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DQN._train_body of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f9b06b425f8>>: AssertionError: Bad argument number for Name: 3, expecting 4

**Comment by keiohta** [comment]
Which TensorFlow version are you using?

**Comment by XiuYuanInTheQuest** [comment]
Same as you 2.0.0b0，but I don't have gpu

**Comment by keiohta** [comment]
Hmm... mine is the same environment, but it works. Can you give me the full log? It might help.

```bash
$ conda list | grep tensorflow
tensorflow                2.0.0b0                   <pip>
$ python experiments/run_dqn.py
 python examples/run_dqn.py
2019-09-23 20:37:10.314242: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
20:37:10.401 [INFO] (trainer.py:104) Total Epi:     1 Steps:      26 Episode Steps:    26 Return:  26.0000 FPS: 3798.39
20:37:10.404 [INFO] (trainer.py:104) Total Epi:     2 Steps:      39 Episode Steps:    13 Return:  13.0000 FPS: 26164.08
20:37:10.404 [INFO] (trainer.py:104) Total Epi:     3 Steps:      50 Episode Steps:    11 Return:  11.0000 FPS: 28926.23

...

20:37:13.879 [INFO] (trainer.py:104) Total Epi:   171 Steps:    2519 Episode Steps:   200 Return:  200.0000 FPS: 954.37
20:37:14.089 [INFO] (trainer.py:104) Total Epi:   172 Steps:    2719 Episode Steps:   200 Return:  200.0000 FPS: 956.17
20:37:14.299 [INFO] (trainer.py:104) Total Epi:   173 Steps:    2919 Episode Steps:   200 Return:  200.0000 FPS: 951.93
```

**Comment by XiuYuanInTheQuest** [comment]
![QQ图片20190927191133](https://user-images.githubusercontent.com/44158381/65765383-af8bed00-e15a-11e9-9dda-4519724046d0.png)

**Comment by XiuYuanInTheQuest** [comment]
I am very sorry to reply to you so late. I am busy with the company recently and did not follow up reinforcement learning!!

**Comment by XiuYuanInTheQuest** [comment]
![QQ图片20190927191333](https://user-images.githubusercontent.com/44158381/65765671-7dc75600-e15b-11e9-8ed5-9145cda30244.png)

**Comment by keiohta** [comment]
I updated master branch to compatible with latest TensorFlow, so can you try with latest master and tensorflow==2.0.0?

**Comment by XiuYuanInTheQuest** [comment]
Alright. Thank you.


发自我的iPhone

------------------ Original ------------------

**Comment by XiuYuanInTheQuest** [comment]
Alright. Thank you for your help.

**Comment by keiohta** [comment]
Hi @XiuYuanInTheQuest, I would close this issue because your initial question has been answered.
If you have any difficulty installing/trying this repository, feel free to open new issue :)
