### ISSUE TITLE
Adding noise to action in DDPG implementation

### ISSUE THREAD

**Issue by benquick123** [keiohta/tf2rl#56]
Hi, 

I noticed another thing. In `DDPG` implementation, there is a method `get_action()` that I think by accident doesn't add noise to action in training phase, but adds it during testing. Here's the exact line that I think is problematic:
https://github.com/keiohta/tf2rl/blob/1badc2a0799de5d08a4a88ef7c4127f4a370d0bf/tf2rl/algos/ddpg.py#L100

As per original pseudocode in original paper [DDPG, page 5](https://arxiv.org/pdf/1509.02971.pdf), it is explicitly stated that noise is added during training. I'm assuming actor's action is then directly used during testing.

**Comment by keiohta** [comment]
Oh... that's exactly a bug, I intended to add noise during training, but it's not.
I'll fix and also compare results between current version and fixed version.
Thank you for reporting this!

**Comment by benquick123** [comment]
That's the weird thing... When training, it still somehow converges to a satisfiable degree.

**Comment by keiohta** [comment]
Yeah, I actually use this implementation in various projects such as [this post](https://keiohta.github.io/posts/rl/safegym/) (sorry for Japanese), but it works, so I did not notice the bug.
Anyway I'll compare results tomorrow and post here.

**Comment by keiohta** [comment]
Above commits fixes this issue.
Thank you @benquick123 for reporting this!
