### ISSUE TITLE
Format of trained trajectory file

### ISSUE THREAD

**Issue by trabant70** [keiohta/tf2rl#61]
Hello Mr. Kei Ohta,

I am very interested to test your library for a reinforcement learning task. Fortunately, I have a set of rules that will allow me to create a potential trajectory external to this code base (no need to capture trainer path directly). Would you be able to add a comment to your explanations as to the format the trajectory file has, so that I can create it externally and read it into the GAIL model? I tried to extract it from the code but got lost in the buffer replay lines. I am still learning. You appear to be the first implementor of a GAIL approach for Tensorflow2. Stable baselines has not yet caught up to TF2.

Thank you,

Reno Fiedler

**Comment by keiohta** [comment]
Hi @trabant70!

All right, I understand your situation. First, you can train GAIL with following commands (this does not solve your problem, just FYI):
```bash
# Generate expert data under results directory
$ python examples/run_sac.py --env-name=RoboschoolReacher-v1 --save-test-path --test-interval=50000

# You'll find generated expert data under `results` directory, in my case  `results/20191201T133044.843033_SAC_`
$ find results/20191201T133044.843033_SAC_ -name *.pkl
results/20191201T133044.843033_SAC_/step_00050000_epi_03_return_00017.8076.pkl
results/20191201T133044.843033_SAC_/step_00050000_epi_00_return_00017.3748.pkl
results/20191201T133044.843033_SAC_/step_00050000_epi_01_return_00023.1999.pkl
results/20191201T133044.843033_SAC_/step_00050000_epi_04_return_00011.9360.pkl
results/20191201T133044.843033_SAC_/step_00050000_epi_02_return_00032.9966.pkl

# Run GAIL
$ python examples/run_gail_ddpg.py --expert-path-dir results/20191201T133044.843033_SAC_
```

To answer your question, you just need to pass expert observations and expert actions to `IRLTrainer`.
So, please modify the final 5 lines of [run_gail_ddpg.py](https://github.com/keiohta/tf2rl/blob/master/examples/run_gail_ddpg.py) as:

```python
    # Get expert observations and actions from your externally created trajectories
    expert_obses, expert_acts = your_custom_method()

    # Check the shape of your expert trajectories
    assert expert_obses.ndim == 2 and expert_obses.shape[1] == env.observation_space.shape[0]
    assert expert_acts.ndim == 2 and expert_acts.shape[1] == env.action_space.shape[0]
    assert expert_obses.shape[0] == expert_acts.shape[0]

    trainer = IRLTrainer(policy, env, args, irl, expert_obses, expert_acts, test_env)
    trainer()
```

If you have other question, please let me know.

**Comment by keiohta** [comment]
Hi @trabant70, I would close this issue because the information above should be enough for your use.
If you have other questions or need help, please reopen this issue or open a new issue.
Thanks!
