### ISSUE TITLE
implementation on windows

### ISSUE THREAD

**Issue by Elfits** [keiohta/tf2rl#65]
Hi Ohta,

Very impressive work!! I guess you development them on Linux rather than Windows. I tried to install your project on Windows but I failed. It seems to be the cpprb lib you used which cannot be used on Windows. I tried a lot on the cython work converting pyx to pyd but not succeed. Do you have some practical suggestions?

I want to use Windows because of our requirement of one software.

**Comment by keiohta** [comment]
Hi @Elfits, thank you for trying to use tf2rl!

I would suggest open an issue on [cpprb](https://gitlab.com/ymd_h/cpprb).
I guess the author might have some work around to make it work on Windows.

**Comment by Elfits** [comment]
Thanks! Good suggestion.
Because when installing your work, it fails saying "cannot make wheel for cpprb"

**Comment by keiohta** [comment]
Yeah, building cython/cpp codes on Windows is always hard...
Hope the author has good solution!

**Comment by Elfits** [comment]
Hi 太田，
I am back. It works now!
Here is the issue on cpprb project. https://gitlab.com/ymd_h/cpprb/issues/67

**Comment by keiohta** [comment]
Great job!!!

I would close this issue because the problem seems to be solved.
Please open a new issue if you have any difficulty using tf2rl, or find some problem or feature request.
