### ISSUE TITLE
DDPG implementation problem

### ISSUE THREAD

**Issue by ymd-h** [keiohta/tf2rl#69]
I've read (mainly) DDPG implementation and found some problem including bug.

1.  Specify mutable object (`list`) as default argument
1.  Make a 0-deviated rondom noise
1.  Don't call `on_episode_end`
1.  Actor/Critic (also in other algorithms) have a lot of duplicated code

---

1.  In CPython default argument are evaluated only once and is reused in multiple calling, so that if you specify mutable like `list` and modify it, then the modification will affect your next construction, too. Usually it is a bug.
1.  Pseudo-random number generation is usually heavy task, it can be non-negligible when the shape is big. When test-mode, you can skip it.
1.  cpprb requires calling `on_episode_end` at the end of episode. Precisely speaking, it is not necessary as long as you don't use Nstep feature, but your `Trainer` is universal, it is a bug.
1.  Many algorithm uses duplicated code, which will be code maintenance problem. (I already saw some inconsistence.)

**Comment by keiohta** [comment]
Thanks, I fixed them.
