### ISSUE TITLE
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'

### ISSUE THREAD

**Issue by jahad9819jjj** [keiohta/tf2rl#72]
Our environment is below.
OS: Ubuntu18.0.4
Python:Python 3.6.9 
tensorflow: tensorflow-gpu 2.0.0 
roboschool: roboschool-1.0.49

We execute this command on `tf2rl`.
```
pip3 install . --user
```
and then
```
python3 run_ddpg.py
```

We receive this error.
```
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
```

How do I fix?

**Comment by keiohta** [comment]
Hi @jahad9819jjj, could you try following command and let me know the result?
```
$ python run_ddpg.py --gpu -1 --env-name Pendulum-v0
$ pip list | grep roboschool
```bash

I have not seen the bug, and suspecting the bug is related to roboschool env.

**Comment by keiohta** [comment]
I found an [article](https://qiita.com/Tarooo000/items/2560b481701a6db8c416) that solves your issue as:

```
$ sudo apt install libtinfo5
```

You can also check an [issue](https://github.com/tensorflow/tensorflow/issues/19375)  on TensorFlow that solves the same problem.

Anyway, it doesn't seem that your bug is caused by tf2rl.

**Comment by jahad9819jjj** [comment]
Hi, @keiohta 

I executed 
```
sudo apt install libtinfo5
```
However, it doesn't work well.
So I wonder your first suggestion is true but I don't have PC. I will report whether it works well or not.

Thanks!

**Comment by jahad9819jjj** [comment]
Sorry for replying late.
I execute 
```
python run_ddpg.py --gpu -1 --env-name Pendulum-v0
``` 
However, it doesn't work well.
So I retry this repository on new environment or docker.
thanks!

**Comment by keiohta** [comment]
I would suggest to test whether you can import TensorFlow or not.
FYI, I also use Ubuntu18.04 with Anaconda, and works well :)

If you need any help, please let me know!

**Comment by AndreasLuckert** [comment]
So far nothing of the above-mentioned steps resolved my problem.

As for my issue:

```
user:~/$ jupyter qtconsole
/home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3.8:
Relink `/usr/lib/x86_64-linux-gnu/libQtCore.so.4' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
```

**Comment by keiohta** [comment]
Hi @AndreasLuckert , I would not think this problem is related to tf2rl.

We ensure that current version works on:
- python: 3.6, 3.7, 3.8
- OS: Ubuntu, Mac OSX, Windows (latest)
- TF: 2.0, 2.1, 2.2, 2.3.

If you can provide more details, I might be able to help you.

**Comment by AndreasLuckert** [comment]
_My details are (if more are needed, please let me know):_

- **Python version:**
Python 3.8.5 (default, Jul 22 2020, 18:54:26) 
[GCC 5.4.0 20160609] on linux

- **OS:**
Linux Lubuntu 18.04 LTS

- User:~/$ **jupyter --version**
```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.1
qtconsole        : 4.7.5
ipython          : 7.17.0
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
```

**Comment by ymd-h** [comment]
Hi @AndreasLuckert,

I feel your problem is not related with tf2rl nor tensorflow, but jupyter qtconsole. (Because you have not executed them at all, right?)
In my opinion, it is better to ask jupyter qtconsole developers. (sorry, I don't know where.)


I think this relink problem comes from some library installation problems. (Links to the dynamic library "librt", where "clock_gettime" is defined, seems to be incorrect or missing.)
Installing additional packages might fix the problem, but it depends on what library you want to run.

**Comment by AndreasLuckert** [comment]
Hey @keiohta and @ymd-h ,

thanks for your comments so far.

Why can't I just follow the above-mentioned error output instructions and

> Relink `/usr/lib/x86_64-linux-gnu/libQtCore.so.4' with `/lib/x86_64-linux-gnu/librt.so.1' ?

I could imagine something like
`ln -s /usr/lib/x86_64-linux-gnu/libQtCore.so.4 /lib/x86_64-linux-gnu/librt.so.1` ,
but I'm unsure if that's feasible without wreaking havoc.

Actually, as an aside, when searching for this `clock_gettime` - function just in the directory `/usr/lib/x86_64-linux-gnu/`
I get loads of matches as can be seen in the following excerpt:

```
User:~/$ grep --exclude-dir='.history' -Rinw /usr/lib/x86_64-linux-gnu/ -e 'clock_gettime'
Binary file /usr/lib/x86_64-linux-gnu/libdirect-1.7.so.7.0.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libavutil.so.55.78.100 matches
Binary file /usr/lib/x86_64-linux-gnu/libjackserver.so.0.1.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libgviewv4l2core-2.0.so.2 matches
Binary file /usr/lib/x86_64-linux-gnu/libopencv_core.so matches
Binary file /usr/lib/x86_64-linux-gnu/fwupd-plugins-3/libfu_plugin_synapticsmst.so matches
Binary file /usr/lib/x86_64-linux-gnu/libwayland-client.so matches
Binary file /usr/lib/x86_64-linux-gnu/jni/libjfxwebkit.so matches
Binary file /usr/lib/x86_64-linux-gnu/jni/libgstreamer-lite.so matches
Binary file /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10 matches
Binary file /usr/lib/x86_64-linux-gnu/libdbus-1.a matches
Binary file /usr/lib/x86_64-linux-gnu/libmpi.so.20 matches
Binary file /usr/lib/x86_64-linux-gnu/libcogl.so.20 matches
Binary file /usr/lib/x86_64-linux-gnu/libzmq.so.5.1.5 matches
Binary file /usr/lib/x86_64-linux-gnu/libsnmp.so.30.0.3 matches
Binary file /usr/lib/x86_64-linux-gnu/libc.a matches
Binary file /usr/lib/x86_64-linux-gnu/libavutil.a matches
Binary file /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28 matches
Binary file /usr/lib/x86_64-linux-gnu/libopencv_videoio.so.3.2.0 matches
Binary file /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstcoretracers.so matches
Binary file /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvideo4linux2.so matches
Binary file /usr/lib/x86_64-linux-gnu/libsamba-util.so.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libasan.so.4 matches
Binary file /usr/lib/x86_64-linux-gnu/samba/libsmbd-base.so.0 matches
Binary file /usr/lib/x86_64-linux-gnu/samba/libmessages-dgm.so.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.5 matches
Binary file /usr/lib/x86_64-linux-gnu/liblttng-ust.so.0.0.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libxatracker.so.2.5.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libglut.so.3.9.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0.1405.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libgfortran.so.5 matches
Binary file /usr/lib/x86_64-linux-gnu/libjacknet.so.0.1.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libcurl.so.4.5.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 matches
Binary file /usr/lib/x86_64-linux-gnu/libssh-gcrypt.so.4.5.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libcups.so.2 matches
Binary file /usr/lib/x86_64-linux-gnu/libfabric.so.1.9.3 matches
Binary file /usr/lib/x86_64-linux-gnu/dri/radeon_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/i965_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/iris_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/nouveau_vieux_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/i915_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/kms_swrast_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/virtio_gpu_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/r200_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/r600_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/dri/r300_dri.so matches
Binary file /usr/lib/x86_64-linux-gnu/libinput.so.10 matches
Binary file /usr/lib/x86_64-linux-gnu/libcairo.so matches
Binary file /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so.20.10.1 matches
Binary file /usr/lib/x86_64-linux-gnu/openmpi/lib/libopen-pal.so.20.10.1 matches
Binary file /usr/lib/x86_64-linux-gnu/libOSMesa.so.8.0.0 matches
Binary file /usr/lib/x86_64-linux-gnu/liblttng-ust.so.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libcurl.so.4 matches
Binary file /usr/lib/x86_64-linux-gnu/libjackserver.so.0 matches
Binary file /usr/lib/x86_64-linux-gnu/libdrm.so matches
Binary file /usr/lib/x86_64-linux-gnu/libopen-pal.so.20 matches
/usr/lib/x86_64-linux-gnu/perl/5.26.1/Time/HiRes.pm:13:          getitimer setitimer nanosleep clock_gettime clock_getres
/usr/lib/x86_64-linux-gnu/perl/5.26.1/Time/HiRes.pm:58:     ($i eq 'clock_gettime'   && !&d_clock_gettime)   ||
/usr/lib/x86_64-linux-gnu/perl/5.26.1/Time/HiRes.pm:95:               clock_gettime clock_getres clock_nanosleep clock
/usr/lib/x86_64-linux-gnu/perl/5.26.1/Time/HiRes.pm:123:  use Time::HiRes qw( clock_gettime clock_getres clock_nanosleep
/usr/lib/x86_64-linux-gnu/perl/5.26.1/Time/HiRes.pm:127:  $realtime   = clock_gettime(CLOCK_REALTIME);
/usr/lib/x86_64-linux-gnu/perl/5.26.1/Time/HiRes.pm:348:=item clock_gettime ( $which )
/usr/lib/x86_64-linux-gnu/perl/5.26.1/Time/HiRes.pm:367:of C<CLOCK_REALTIME>, see L</clock_gettime>.
/usr/lib/x86_64-linux-gnu/perl/5.26.1/Time/HiRes.pm:371:be able to specify the arguments to clock_gettime() and clock_nanosleep()
/usr/lib/x86_64-linux-gnu/perl/5.26.1/Time/HiRes.pm:380:"clock id", as with clock_gettime() and clock_getres().  The flags
/usr/lib/x86_64-linux-gnu/perl/5.26.1/Time/HiRes.pm:523:  use Time::HiRes qw( clock_gettime clock_getres CLOCK_REALTIME );
....
```

**Comment by ymd-h** [comment]
@AndreasLuckert 

Please, let me confirm. Do you still think that your problem comes from tf2rl?
I think your Qt installation is broken (and your problem is different problem from the original topic of this issue).

Qt is a GUI library and t2rl developers don't know detail. (We don't develop any GUI applications.)


> ln -s /usr/lib/x86_64-linux-gnu/libQtCore.so.4 /lib/x86_64-linux-gnu/librt.so.1

Never do that. I don't think link means symbolic link but a job of linker (e.g. ld).

**Comment by AndreasLuckert** [comment]
> Please, let me confirm. Do you still think that your problem comes from tf2rl?

No, I haven't had any idea what might be the cause.

> Never do that. I don't think link means symbolic link but a job of linker (e.g. ld).
You're completely right, I wasn't going to actually do that, but wanted to hypothesize something similar to what could be a viable approach, if there is any.


To sum up, thanks for your hints and tipps.
I'm hoping for further help under my [issue](https://github.com/jupyter/qtconsole/issues/432) posted on the `jupyter qtconsole` GitHub-page.
If anyone reading this knows the answer, feel free to let me know :)
