### ISSUE TITLE
Continue training from restored model

### ISSUE THREAD

**Issue by cambel** [keiohta/tf2rl#74]
Hi, thanks for the repo. I have been testing it and so far it works fine for me.

I played with the save and restore functions, and I can restore a model and change the arguments         `n_warmup, max_steps, test_interval, evaluate` so that it actually evaluates using the restored model. I set a very small test_interval and max_steps for the evaluation to be executed. 

However, if I want to continue training, it seems to not use the restored model, i.e with a usual max_steps and test_interval; It goes to be as bad as starting from scratch. 
is there a way load the trained model before starting the training so the learned parameters are used from the beginning?

**Comment by keiohta** [comment]
Hi @cambel, I could not reproduce your problem with SAC on Pendulum-v0 environment.

```bash
$ python examples/run_sac.py --env-name Pendulum-v0 --n-warmup 500 --max-steps 50000 --memory-capacity 10000 --gpu -1
$ ls results/20200108T191338.721946_SAC_/
...
checkpoint
ckpt-5.data-00000-of-00001
ckpt-5.index
...
$ python examples/run_sac.py --env-name Pendulum-v0 --n-warmup 500 --max-steps 50000 --memory-capacity 10000 --gpu -1 --model-dir results/20200108T191338.721946_SAC_/
```

The orange line is trained from scratch, and blue line is trained from restored model. As you can see from `SAC/actor_loss`, `SAC/critic_Q_loss`, and `SAC/critic_V_loss`, learning curves immediately converges nearly to the same values on trained model from scratch.

![issue_74_reproduce](https://user-images.githubusercontent.com/7234712/71970819-be4f6900-324c-11ea-9d09-4a0e61f4c790.png)

The reason why initial loss is not as low as converged value is that initial sample contains random values, where distribution mismatch occurs (random values are sampled from uniform distribution).

If you can provide an example to reproduce your problem, please let me know. I will look into the problem :)

**Comment by cambel** [comment]
Hi @keiohta, thank you, I am working on a custom environment so it was harder to see if the agent was converging to the previously learned model but I think is working.
