### ISSUE TITLE
Ask about GPU settings

### ISSUE THREAD

**Issue by lichongcoco** [keiohta/tf2rl#81]
I see that the CPU is specified in many places in the code:

`with tf.device ("/ cpu: 0")`

So does setting the GPU still take effect?

`parser.set_defaults (gpu = 0)`

**Comment by keiohta** [comment]
Yes, it should be. I explicitly use `cpu` only when initializes the network which is not computationally heavy because it causes only one forward propagation.

**Comment by lichongcoco** [comment]
Thank you very much for your answer
