### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by sfornengo** [keiohta/tf2rl#87]
Just trying to import:
from tf2rl.experiments.trainer import Trainer

Give me "illegal instruction (core dumped)"
using tf2rl v0.1.12 on python v3.8.2

**Comment by yamada-github-account** [comment]
Hi, @sfornengo 

Can you check `import tensorflow as tf` directly?

Recent TensorFlow pre-built binary requires AVX support.
Without AVX (old CPU), such error massage will be issued.

https://stackoverflow.com/questions/49094597/illegal-instruction-core-dumped-after-running-import-tensorflow

**Comment by sfornengo** [comment]
Thanks.
No problem with  `import tensorflow as tf`
with tensorflow 2.20 installed.

my cpu is not new but `grep avx /proc/cpuinfo` gives me:
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 popcnt aes xsave avx lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt fma4 nodeid_msr topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold

**Comment by sfornengo** [comment]
The culprit inside trainer.py seems to be this import:
`from tf2rl.misc.get_replay_buffer import get_replay_buffer`

**Comment by sfornengo** [comment]
And then in get_replay_buffer.py the illegal instruction is generated by:
`from cpprb import ReplayBuffer`

**Comment by sfornengo** [comment]
Downgrading cpprb to version 8.1 solve the problem.

**Comment by yamada-github-account** [comment]
It seems that pre-built cpprb binary is not match with your platform for some reason.

Please try `pip install cpprb --no-binary` to install from source code.

**Comment by sfornengo** [comment]
Good catch, `pip install cpprb --no-binary` works.
Thanks
