### ISSUE TITLE
SAC_Discrete does not learn for Acrobot v1

### ISSUE THREAD

**Issue by cubicgate** [keiohta/tf2rl#88]
Hi @keiohta,

  Thanks for your code! I tried your SAC_Discrete on Acrobot V1, and it seems does not learn:

  19:00:22.913 [INFO] (trainer_acrobot.py:111) Total Epi:     1 Steps:     500 Episode Steps:   500 Return: -500.0000 FPS: 3662.83
19:00:32.307 [INFO] (trainer_acrobot.py:111) Total Epi:     2 Steps:    1000 Episode Steps:   500 Return: -500.0000 FPS: 53.26
19:00:38.356 [INFO] (trainer_acrobot.py:111) Total Epi:     3 Steps:    1500 Episode Steps:   500 Return: -500.0000 FPS: 82.74
19:00:44.421 [INFO] (trainer_acrobot.py:111) Total Epi:     4 Steps:    2000 Episode Steps:   500 Return: -500.0000 FPS: 82.52
19:00:47.450 [INFO] (trainer_acrobot.py:139) Evaluation Total Steps:    2000 Average Reward -500.0000 over  5 episodes
19:00:53.582 [INFO] (trainer_acrobot.py:111) Total Epi:     5 Steps:    2500 Episode Steps:   500 Return: -500.0000 FPS: 54.60
19:00:59.706 [INFO] (trainer_acrobot.py:111) Total Epi:     6 Steps:    3000 Episode Steps:   500 Return: -500.0000 FPS: 81.70
19:01:06.051 [INFO] (trainer_acrobot.py:111) Total Epi:     7 Steps:    3500 Episode Steps:   500 Return: -500.0000 FPS: 78.85
19:01:12.452 [INFO] (trainer_acrobot.py:111) Total Epi:     8 Steps:    4000 Episode Steps:   500 Return: -500.0000 FPS: 78.16
19:01:16.248 [INFO] (trainer_acrobot.py:139) Evaluation Total Steps:    4000 Average Reward -500.0000 over  5 episodes
19:01:23.372 [INFO] (trainer_acrobot.py:111) Total Epi:     9 Steps:    4500 Episode Steps:   500 Return: -500.0000 FPS: 45.81
19:01:29.756 [INFO] (trainer_acrobot.py:111) Total Epi:    10 Steps:    5000 Episode Steps:   500 Return: -500.0000 FPS: 78.38
19:01:36.342 [INFO] (trainer_acrobot.py:111) Total Epi:    11 Steps:    5500 Episode Steps:   500 Return: -500.0000 FPS: 75.96
19:01:42.552 [INFO] (trainer_acrobot.py:111) Total Epi:    12 Steps:    6000 Episode Steps:   500 Return: -500.0000 FPS: 80.63
19:01:45.675 [INFO] (trainer_acrobot.py:139) Evaluation Total Steps:    6000 Average Reward -500.0000 over  5 episodes
19:01:51.657 [INFO] (trainer_acrobot.py:111) Total Epi:    13 Steps:    6500 Episode Steps:   500 Return: -500.0000 FPS: 54.94
19:01:57.931 [INFO] (trainer_acrobot.py:111) Total Epi:    14 Steps:    7000 Episode Steps:   500 Return: -500.0000 FPS: 79.77
19:02:04.037 [INFO] (trainer_acrobot.py:111) Total Epi:    15 Steps:    7500 Episode Steps:   500 Return: -500.0000 FPS: 81.94
19:02:10.050 [INFO] (trainer_acrobot.py:111) Total Epi:    16 Steps:    8000 Episode Steps:   500 Return: -500.0000 FPS: 83.26
19:02:13.156 [INFO] (trainer_acrobot.py:139) Evaluation Total Steps:    8000 Average Reward -500.0000 over  5 episodes
19:02:19.189 [INFO] (trainer_acrobot.py:111) Total Epi:    17 Steps:    8500 Episode Steps:   500 Return: -500.0000 FPS: 54.73
19:02:25.230 [INFO] (trainer_acrobot.py:111) Total Epi:    18 Steps:    9000 Episode Steps:   500 Return: -500.0000 FPS: 82.84
19:02:31.316 [INFO] (trainer_acrobot.py:111) Total Epi:    19 Steps:    9500 Episode Steps:   500 Return: -500.0000 FPS: 82.22
19:02:37.496 [INFO] (trainer_acrobot.py:111) Total Epi:    20 Steps:   10000 Episode Steps:   500 Return: -500.0000 FPS: 81.02
19:02:40.512 [INFO] (trainer_acrobot.py:139) Evaluation Total Steps:   10000 Average Reward -500.0000 over  5 episodes
19:02:46.878 [INFO] (trainer_acrobot.py:111) Total Epi:    21 Steps:   10500 Episode Steps:   500 Return: -500.0000 FPS: 53.32
19:02:54.265 [INFO] (trainer_acrobot.py:111) Total Epi:    22 Steps:   11000 Episode Steps:   500 Return: -500.0000 FPS: 67.75
19:03:01.239 [INFO] (trainer_acrobot.py:111) Total Epi:    23 Steps:   11500 Episode Steps:   500 Return: -500.0000 FPS: 71.75
19:03:07.483 [INFO] (trainer_acrobot.py:111) Total Epi:    24 Steps:   12000 Episode Steps:   500 Return: -500.0000 FPS: 80.18
19:03:10.750 [INFO] (trainer_acrobot.py:139) Evaluation Total Steps:   12000 Average Reward -500.0000 over  5 episodes
19:03:16.858 [INFO] (trainer_acrobot.py:111) Total Epi:    25 Steps:   12500 Episode Steps:   500 Return: -500.0000 FPS: 53.36
19:03:22.977 [INFO] (trainer_acrobot.py:111) Total Epi:    26 Steps:   13000 Episode Steps:   500 Return: -500.0000 FPS: 81.78
19:03:29.044 [INFO] (trainer_acrobot.py:111) Total Epi:    27 Steps:   13500 Episode Steps:   500 Return: -500.0000 FPS: 82.48
19:03:35.167 [INFO] (trainer_acrobot.py:111) Total Epi:    28 Steps:   14000 Episode Steps:   500 Return: -500.0000 FPS: 81.73
19:03:38.204 [INFO] (trainer_acrobot.py:139) Evaluation Total Steps:   14000 Average Reward -500.0000 over  5 episodes
19:03:44.273 [INFO] (trainer_acrobot.py:111) Total Epi:    29 Steps:   14500 Episode Steps:   500 Return: -500.0000 FPS: 54.94
19:03:50.363 [INFO] (trainer_acrobot.py:111) Total Epi:    30 Steps:   15000 Episode Steps:   500 Return: -500.0000 FPS: 82.17
19:03:56.652 [INFO] (trainer_acrobot.py:111) Total Epi:    31 Steps:   15500 Episode Steps:   500 Return: -500.0000 FPS: 79.57
19:04:02.765 [INFO] (trainer_acrobot.py:111) Total Epi:    32 Steps:   16000 Episode Steps:   500 Return: -500.0000 FPS: 81.84
19:04:05.828 [INFO] (trainer_acrobot.py:139) Evaluation Total Steps:   16000 Average Reward -500.0000 over  5 episodes
19:04:11.879 [INFO] (trainer_acrobot.py:111) Total Epi:    33 Steps:   16500 Episode Steps:   500 Return: -500.0000 FPS: 54.90
19:04:18.074 [INFO] (trainer_acrobot.py:111) Total Epi:    34 Steps:   17000 Episode Steps:   500 Return: -500.0000 FPS: 80.77
19:04:24.186 [INFO] (trainer_acrobot.py:111) Total Epi:    35 Steps:   17500 Episode Steps:   500 Return: -500.0000 FPS: 81.87
19:04:30.283 [INFO] (trainer_acrobot.py:111) Total Epi:    36 Steps:   18000 Episode Steps:   500 Return: -500.0000 FPS: 82.09
19:04:33.354 [INFO] (trainer_acrobot.py:139) Evaluation Total Steps:   18000 Average Reward -500.0000 over  5 episodes
19:04:39.532 [INFO] (trainer_acrobot.py:111) Total Epi:    37 Steps:   18500 Episode Steps:   500 Return: -500.0000 FPS: 54.09
19:04:45.674 [INFO] (trainer_acrobot.py:111) Total Epi:    38 Steps:   19000 Episode Steps:   500 Return: -500.0000 FPS: 81.48
19:04:51.823 [INFO] (trainer_acrobot.py:111) Total Epi:    39 Steps:   19500 Episode Steps:   500 Return: -500.0000 FPS: 81.44
19:05:23.717 [INFO] (trainer_acrobot.py:111) Total Epi:    40 Steps:   20000 Episode Steps:   500 Return: -500.0000 FPS: 82.34
19:05:26.775 [INFO] (trainer_acrobot.py:139) Evaluation Total Steps:   20000 Average Reward -500.0000 over  5 episodes
19:05:32.876 [INFO] (trainer_acrobot.py:111) Total Epi:    41 Steps:   20500 Episode Steps:   500 Return: -500.0000 FPS: 54.62
19:05:38.917 [INFO] (trainer_acrobot.py:111) Total Epi:    42 Steps:   21000 Episode Steps:   500 Return: -500.0000 FPS: 82.86
19:05:44.885 [INFO] (trainer_acrobot.py:111) Total Epi:    43 Steps:   21500 Episode Steps:   500 Return: -500.0000 FPS: 83.88
19:05:50.910 [INFO] (trainer_acrobot.py:111) Total Epi:    44 Steps:   22000 Episode Steps:   500 Return: -500.0000 FPS: 83.04
19:05:53.911 [INFO] (trainer_acrobot.py:139) Evaluation Total Steps:   22000 Average Reward -500.0000 over  5 episodes
19:05:59.898 [INFO] (trainer_acrobot.py:111) Total Epi:    45 Steps:   22500 Episode Steps:   500 Return: -500.0000 FPS: 55.66
19:06:05.862 [INFO] (trainer_acrobot.py:111) Total Epi:    46 Steps:   23000 Episode Steps:   500 Return: -500.0000 FPS: 83.91

  Thanks for your help!

**Comment by keiohta** [comment]
Thanks for the report!
I successfully reproduced the error, and also confirmed it can be solved using DQN.
I'll take a look into this and report later.

**Comment by cubicgate** [comment]
Thanks @keiohta for your help!

**Comment by keiohta** [comment]
Hi @cubicgate! Sorry for late reply.
I investigated the problem, and I conclude that the low performance is caused by bad exploration of discrete-SAC.

<img width="1152" alt="Screen Shot 2020-07-02 at 23 39 56" src="https://user-images.githubusercontent.com/7234712/86372511-38711f80-bcbd-11ea-8b49-7ece1632461e.png">

As you can see the above TensorBoard screenshot, I ran 10 times with random seeds, and it successfully learns four times.
Since the reward design of Acrobot-v1 environment is kind of sparse (only 0 reward when it satisfies a termination condition, and -1 otherwise), the agent does not acquire information to control towards high reward in many situations.

I think we would be able to mitigate this problem by following ways:
- Increase `n_warmup` that defines number of steps before updating policy, and forces producing completely random action
- Increase entropy coefficient of the agent to encourage exploration during training (that also prevents from converging to non-optimal solution)

If you want me to try those things, I would say it takes time (because I've been busy these days..).

**Comment by cubicgate** [comment]
Thanks @keiohta for your kindness to help me. It is not necessary for you to spend more time on this matter if you are busy right now.  Thanks again!
