### ISSUE TITLE
Performance of PPO to 'PongNoFrameskip-v4'

### ISSUE THREAD

**Issue by Callmejp** [keiohta/tf2rl#90]
Hi, keiohta!

Your work is so impressive!

When l try the [run_ppo_atari.py](https://github.com/keiohta/tf2rl/blob/master/examples/run_ppo_atari.py) in `examples`, l can't get satisfying result.

And differences in my code are that 
1. l use `list` to replace the functions of `cpprb`, and store the `obs.__array__()` in  `list`. 
2. l don't use random sample(just draw the latest 1024(horizion) samples).
The rest hyperparameters are the same as the `run_ppo_atari.py`.

And my result is listed below(With ≈ 0.1M steps, the episode reward is still ≈ -21.0):
```
19:56:21.327 [INFO] (on_policy_trainer.py:77) Total Epi:   112 Steps:   98207 Episode Steps:   762 Return: -21.0000 FPS: 141.92
19:56:45.970 [INFO] (on_policy_trainer.py:77) Total Epi:   113 Steps:   99141 Episode Steps:   934 Return: -20.0000 FPS: 37.90
19:57:11.972 [INFO] (on_policy_trainer.py:77) Total Epi:   114 Steps:  100106 Episode Steps:   965 Return: -19.0000 FPS: 37.12
19:57:35.226 [INFO] (on_policy_trainer.py:77) Total Epi:   115 Steps:  100977 Episode Steps:   871 Return: -21.0000 FPS: 37.46
19:57:57.435 [INFO] (on_policy_trainer.py:77) Total Epi:   116 Steps:  101799 Episode Steps:   822 Return: -21.0000 FPS: 37.01
19:58:24.727 [INFO] (on_policy_trainer.py:87) Evaluation Total Steps:  102400 Average Reward -21.0000 over  5 episodes
```

To be honest, l don't have much experience in the RL baseline.  And l can't find your testing results in the repository.  So l want to know whether it's the normal results.

Thanks for any help!!!

**Comment by keiohta** [comment]
Hi @Callmejp , thanks for trying tf2rl!
I think we cannot say PPO does not work well based on just ~0.1M steps of training, so I recommend to try at least 3 million steps. Also, since PPO is on-policy method, it usually needs much more samples than off-policy methods, such as DQN.
In fact, the original paper shows it takes several million steps to see the return increases during training (Figure 6).
https://arxiv.org/pdf/1707.06347.pdf

**Comment by Callmejp** [comment]
After reading your answer, I am a little ashamed of my ignorance. （LOL）
Thanks very much to you!

**Comment by keiohta** [comment]
No, no you don’t need to think like that! I’m very open to any kind of question, so please don’t hesitate to open an issue👍

**Comment by Callmejp** [comment]
Got it!   
^_^
