### ISSUE TITLE
dose the code support MPI to speed up the training?

### ISSUE THREAD

**Issue by zhihaocheng** [keiohta/tf2rl#98]

**Comment by keiohta** [comment]
APE-X type of parallelization which uses multiprocessing API has already been implemented.
https://github.com/keiohta/tf2rl/blob/master/tf2rl/algos/apex.py

Sometimes this speeds up training, but it depends on type of the environment and policy you use.

**Comment by zhihaocheng** [comment]
@keiohta  Thanks a lot. I want to run GAIL, but with the "--help", I still do not know how to config the number of cpu. 

In addition, does the spectral normalization help to improve the performance of GAIL？

**Comment by keiohta** [comment]
@zhihaocheng Sorry for late reply.
We support distributed training only on ApeX style DDPG and DQN. We won't support inverse RL unless we find some interesting paper which uses the distributed version of IRL. However, if you do need to implement the code, you can do referring the apex code I sent you in the previous comment.

> In addition, does the spectral normalization help to improve the performance of GAIL？
I'm sure it improves the performance. Please find below link and compare "accuracy" of discriminator. The lower (closer to 0.5, where discriminator cannot judge whether the inputs come from expert or current agent) the better.
https://github.com/keiohta/tf2rl/issues/14#issuecomment-509034835

**Comment by zhihaocheng** [comment]
@keiohta thanks for your detailed reply, it is really helpful to me.
